const assert = require('node:assert/strict');
const fs = require('node:fs'), path = require('node:path');
module.exports = async (win, uid) => {
  const js = code => win.webContents.executeJavaScript(code);
  const wait = async predicate => {
    const until = Date.now() + 20000;
    while (Date.now() < until) { if (await js(predicate)) return; await new Promise(r => setTimeout(r, 70)); }
    throw new Error('Admin UI: ' + await js("document.getElementById('admin-message').textContent"));
  };
  const fill = values => js(`for (const [id,value] of Object.entries(${JSON.stringify(values)})) document.getElementById(id).value=value`);
  const submit = async id => {
    await js(`document.getElementById('${id}').requestSubmit()`);
    await wait("document.getElementById('admin-dialog').dataset.busy === 'false'");
    assert.match(await js("document.getElementById('admin-message').textContent"), /carregada|Configuração salva|Migração confirmada/);
  };
  await js("document.getElementById('admin-open').click()");
  await fill({ 'admin-shop': 'demo-loja-interface', 'admin-slug': 'recebimento-ui' }); await submit('admin-load');
  await require('./configuracao-mesas-ui.cjs')(win);
  await js("document.getElementById('admin-waiter-invite').closest('details').open=true;document.getElementById('admin-waiter-email').value='convite-ui@example.test';document.getElementById('admin-waiter-invite').requestSubmit()");
  await wait("document.getElementById('admin-dialog').dataset.busy==='false' && document.getElementById('admin-waiter-link').value.includes('#convite=')");
  assert.match(await js("document.getElementById('admin-waiter-link').value"),/^http:\/\/127\.0\.0\.1:5173\/v2\/recebimento-ui\/garcom#convite=/);
  await js("document.getElementById('admin-waiter-revoke-invite').click()");
  await wait("document.getElementById('admin-dialog').dataset.busy==='false' && document.getElementById('admin-message').textContent.includes('Convite revogado')");
  assert.equal(await js("document.getElementById('admin-waiter-link').value"),'');
  console.log('GARCOM CONVITE ADMIN UI PASS: emissão por e-mail e revogação sem envio externo.');
  await js("document.getElementById('admin-delivery').closest('details').open=true;document.getElementById('admin-delivery-add-region').click();document.getElementById('admin-delivery-add-period').click();document.getElementById('admin-delivery-active').checked=true;document.getElementById('admin-delivery-scheduled').checked=true");
  await fill({'admin-delivery-minimum':'12,50','admin-delivery-timezone':'America/Sao_Paulo'});
  await js(`for(const [key,value] of Object.entries({id:'centro-ui',nome:'Centro teste',cepInicial:'01000000',cepFinal:'01999999',taxa:'5,50',prazo:'45'}))document.querySelector('#admin-delivery-regions [data-field='+key+']').value=value`);
  await submit('admin-delivery');
  assert.equal(await js("document.querySelector('#admin-delivery-regions [data-field=taxa]').value"),'5.50');
  assert.equal(await js("document.getElementById('admin-delivery-minimum').value"),'12.50');
  assert.equal(await js("document.getElementById('admin-delivery-scheduled').checked"),true);
  assert.equal(await js("document.querySelector('#admin-delivery-periods [data-field=inicio]').value"),'18:00');
  console.log('DELIVERY CONFIG UI PASS: região, taxa, mínimo, prazo e horário persistidos e recarregados.');

  for(const [estado,revisao] of [['suspensa','1'],['habilitada','2']]) {
    await fill({'admin-activation-choice':estado,'admin-activation-reason':'Conferência de homologação'});
    await js("document.getElementById('admin-activation-confirm').checked=true;document.getElementById('admin-activation-form').requestSubmit()");
    await wait("document.getElementById('admin-dialog').dataset.busy === 'false'");
    assert.equal(await js("document.getElementById('admin-activation-state').dataset.revisao"),revisao);
    await wait("document.getElementById('checkout-dialog').dataset.novasPermitidas === '"+(estado==='habilitada'?'true':'false')+"'");
    assert.equal(await js("document.getElementById('op-add').disabled"),estado==='suspensa'||!(await js("document.getElementById('op-product').value")));
    assert.equal(await js("document.getElementById('classic-pdv-barcode-input').disabled"),estado==='suspensa');
    assert.equal(await js("document.getElementById('admin-activation-confirm').checked"),false);
  }
  await fill({'admin-activation-reason':'Revisão antiga simulada','admin-activation-choice':'suspensa'});
  await js("document.getElementById('admin-activation-state').dataset.revisao='0';document.getElementById('admin-activation-confirm').checked=true;document.getElementById('admin-activation-form').requestSubmit()");
  await wait("document.getElementById('admin-dialog').dataset.busy === 'false'");
  assert.match(await js("document.getElementById('admin-message').textContent"),/mudou/);
  assert.equal(await js("document.getElementById('admin-activation-state').dataset.revisao"),'2');
  assert.equal(await js("document.getElementById('admin-activation-confirm').checked"),false);
  const activationOutput=path.resolve(__dirname,'../../output/etapa-7w');fs.mkdirSync(activationOutput,{recursive:true});const previousSize=win.getSize();
  for(const width of [1366,1024]){win.setSize(width,768);await js("document.getElementById('admin-activation-section').scrollIntoView({block:'start'});new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))");fs.writeFileSync(path.join(activationOutput,'ativacao-'+width+'.png'),(await win.webContents.capturePage(undefined,{stayHidden:true,stayAwake:true})).toPNG());}win.setSize(...previousSize);
  console.log('ATIVACAO UI PASS: suspensão, habilitação, revisão e conflito com nova confirmação.');
  await fill({ 'admin-terminal': uid, 'admin-printer': 'Impressora simulada da cozinha', 'admin-segment': 'padaria' });
  await js("document.getElementById('admin-kds').checked=false"); await submit('admin-modules');
  await wait("document.getElementById('kitchen-kds').hidden === true");
  await js("document.getElementById('admin-kds').checked=true"); await submit('admin-modules');
  await wait("document.getElementById('kitchen-kds').hidden === false");
  await fill({ 'admin-table-id': 'mesa-painel', 'admin-table-name': 'Mesa 88', 'admin-table-number': '88' }); await submit('admin-table');
  await fill({ 'admin-table-select': 'mesa-painel' }); await js("document.getElementById('admin-table-select').dispatchEvent(new Event('change')); document.getElementById('admin-show-qr').click()");
  await wait("document.getElementById('admin-dialog').dataset.busy === 'false'");
  assert.equal(await js("document.getElementById('admin-qr-url').textContent"), 'http://127.0.0.1:5173/v2/recebimento-ui/mesa/mesa-painel');
  assert.ok(await js("document.querySelector('#admin-qr svg') !== null"));
  await fill({ 'admin-product-id': 'agua-painel', 'admin-product-name': 'Água de teste', 'admin-product-price': '3,50', 'admin-product-category':'Bebidas','admin-product-order':'3','admin-product-description':'Água mineral','admin-product-image':'https://res.cloudinary.com/exemplo/image/upload/v1/agua.jpg' }); await submit('admin-product');
  await js("document.getElementById('admin-product-select').value='agua-painel';document.getElementById('admin-product-select').dispatchEvent(new Event('change'))");
  assert.equal(await js("document.getElementById('admin-product-category').value"),'Bebidas');
  assert.equal(await js("document.getElementById('admin-product-order').value"),'3');
  await js("document.getElementById('admin-published').checked=false");await submit('admin-publication');
  assert.match(await js("document.getElementById('admin-publication-state').textContent"),/Fora/);
  await js("document.getElementById('admin-published').checked=true");await submit('admin-publication');
  assert.equal(await js("document.getElementById('admin-published').checked"),true);
  console.log('CATALOGO ADMIN UI PASS: categoria, ordem, descrição, foto e publicação explícita.');
  await fill({ 'admin-option-product': 'agua-painel' }); await js("document.getElementById('admin-option-product').dispatchEvent(new Event('change'))");
  await fill({ 'admin-group-id': 'temperatura', 'admin-group-name': 'Temperatura', 'admin-option-id': 'gelada', 'admin-option-name': 'Gelada' }); await submit('admin-option');
  await fill({ 'admin-stock-id': 'sal-painel', 'admin-stock-name': 'Sal de teste', 'admin-unit': 'kg', 'admin-stock-delta': '2,500', 'admin-stock-reason': 'Saldo inicial do teste' }); await submit('admin-stock');
  await fill({ 'admin-recipe-product': 'agua-painel' }); await js("document.getElementById('admin-recipe-product').dispatchEvent(new Event('change')); document.getElementById('admin-no-stock').checked=true"); await submit('admin-recipe');
  await js("document.getElementById('admin-migration-section').open=true;document.getElementById('admin-migration-section').scrollIntoView({block:'center'})");
  await fill({'admin-migration-product':'farinha-legado-teste'});
  await js("document.getElementById('admin-migration-preview').click()");
  await wait("document.getElementById('admin-dialog').dataset.busy === 'false'");
  assert.match(await js("document.getElementById('admin-migration-plan').textContent"),/2500 g → 2.5 kg/);
  await js("document.getElementById('admin-migration-confirm').checked=true");await submit('admin-migration-form');
  assert.ok(await js("document.getElementById('admin-migration-plan').dataset.estoqueId"));
  assert.equal(await js("(()=>{try{window.StorageService.saveVenda({id:'BLOQUEADA',itens:[{id:'farinha-legado-teste',quantidade:1}]});return false;}catch(e){return e.message.includes('bloqueada');}})()"),true);
  await js("document.getElementById('admin-migration-plan').scrollIntoView({block:'center'})");await new Promise(r=>setTimeout(r,2000));
  const migrationOutput=path.resolve(__dirname,'../../output/etapa-7g');fs.mkdirSync(migrationOutput,{recursive:true});fs.writeFileSync(path.join(migrationOutput,'saldo-migrado.png'),(await win.webContents.capturePage()).toPNG());
  console.log('MIGRACAO UI PASS: 2500 g convertidos em 2,5 kg; venda local bloqueada sem duplicar estoque.');
  await fill({'admin-migration-product':'acucar-legado-teste'});
  await js("document.getElementById('admin-migration-preview').click()");await wait("document.getElementById('admin-dialog').dataset.busy === 'false'");
  await js("document.getElementById('admin-migration-confirm').checked=true");await submit('admin-migration-form');
  await js("document.querySelectorAll('#admin-dialog details').forEach((d,i)=>d.open=i===0); document.getElementById('admin-dialog').scrollTop=0");
  const output = path.resolve(__dirname, '../../output/etapa-6-configuracao'); fs.mkdirSync(output, { recursive: true });
  await win.webContents.capturePage(undefined, { stayHidden: true, stayAwake: true });
  await new Promise(r => setTimeout(r, 800));
  fs.writeFileSync(path.join(output, 'painel-administrativo.png'), (await win.webContents.capturePage(undefined, { stayHidden: true, stayAwake: true })).toPNG());
  await js("document.getElementById('admin-close').click(); document.getElementById('pair-open').click()");
  console.log('ADMIN UI PASS: módulos/KDS ao vivo, terminal, mesa/QR, produto, opção, estoque e ficha.');
};
