const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

module.exports = async function pairingUiFlow(win) {
  const js = code => win.webContents.executeJavaScript(code);
  await require('./seed-turno-ui.cjs')(win);
  const wait = async (code,timeout=22000) => {
    const deadline = Date.now() + timeout;
    while (Date.now() < deadline) { if (await js(code)) return; await new Promise(resolve => setTimeout(resolve, 60)); }
    throw new Error(`UI não concluiu: ${code}; mensagem: ${await js("document.querySelector('#pair-message')?.textContent")}`);
  };
  const action = async code => { await js(code); await wait("document.querySelector('#pair-dialog').dataset.busy === 'false'"); };
  const fill = async fields => js(`for (const [id,value] of Object.entries(${JSON.stringify(fields)})) document.getElementById(id).value=value;`);
  const read = id => js(`document.getElementById(${JSON.stringify(id)}).textContent`);

  async function setHomologacao(estado) {
    await js("document.querySelectorAll('dialog[open]').forEach(d=>d.close());document.getElementById('pair-open').click()");
    await fill({'pair-email':'gerente-ui@example.test','pair-password':'TesteLocal-123!'});
    await action("document.getElementById('pair-login-form').requestSubmit()");
    await js("document.getElementById('pair-close').click();document.getElementById('admin-open').click()");
    await fill({'admin-shop':'demo-loja-interface','admin-slug':'recebimento-ui'});
    await js("document.getElementById('admin-load').requestSubmit()");await wait("document.getElementById('admin-dialog').dataset.busy === 'false' && !document.getElementById('admin-content').hidden");
    await fill({'admin-activation-choice':estado,'admin-activation-reason':'Teste de suspensão com venda pendente'});
    await js("document.getElementById('admin-activation-confirm').checked=true;document.getElementById('admin-activation-form').requestSubmit()");
    await wait("document.getElementById('admin-dialog').dataset.busy === 'false'");
    await wait("document.getElementById('checkout-dialog').dataset.novasPermitidas === '"+(estado==='habilitada'?'true':'false')+"'");
    assert.match(await read('admin-message'),/Alteração confirmada/);
    await js("document.getElementById('admin-close').click();document.getElementById('checkout-open').click()");
  }
  await js("document.getElementById('pair-open').click()");
  await action("document.getElementById('pair-prepare').click()");
  const uid = await js("document.getElementById('pair-uid').value"); assert.ok(uid);
  await fill({ 'pair-email': 'gerente-ui@example.test', 'pair-password': 'TesteLocal-123!' });
  await action("document.getElementById('pair-login-form').requestSubmit()");
  assert.match(await read('pair-manager-state'), /Conectado/);
  assert.equal(await js("document.getElementById('pair-password').value"), '');
  await fill({ 'pair-shop': 'demo-loja-outra', 'pair-target': uid, 'pair-name': 'Balcão de teste' });
  await action("document.getElementById('pair-issue-form').requestSubmit()");
  assert.equal(await js("document.getElementById('pair-message').dataset.error"), 'true');
  await fill({ 'pair-shop': 'demo-loja-interface' });
  await action("document.getElementById('pair-issue-form').requestSubmit()");
  const token = await js("document.getElementById('pair-issued').value"); assert.equal(token.length, 43);
  await fill({ 'pair-token': token });
  await action("document.getElementById('pair-activate-form').requestSubmit()");
  assert.match(await read('pair-terminal-state'), /Terminal ativo/);
  if (await js('window.electronAPI.homologacaoOperacional')) {
    await wait("document.getElementById('checkout-activation').textContent.includes('suspensa')");
    assert.equal(await js("document.getElementById('checkout-dialog').dataset.novasPermitidas"), 'false');
    console.log('ADESAO OPERACIONAL UI PASS: terminal pareado sem adesão não libera novas vendas.');
  }
  assert.equal(await js("!!document.getElementById('modal-ativacao-sistema')"),false);
  await js("document.getElementById('pair-close').click();document.getElementById('checkout-open').click();document.getElementById('server-turn-open').click()");
  await wait("document.getElementById('server-turn-state').dataset.status === 'aberto' && document.getElementById('checkout-dialog').dataset.busy === 'false'");
  await js("document.getElementById('checkout-close').click();document.getElementById('pair-open').click()");
  await wait("document.querySelector('#receive-list').textContent.includes('Sem cebola')");
  assert.match(await read('receive-list'), /Bacon/);
  assert.match(await read('receive-list'), /MESA-1/);
  await wait("document.querySelector('#kitchen-print-list [data-status=simulado]') !== null");
  await wait("document.getElementById('kitchen-preview').srcdoc.includes('Sem cebola')");
  assert.match(await read('kitchen-cards'), /Bacon/);
  await require('./configuracao-ui-flow.cjs')(win, uid);
  await require('./delivery-caixa-ui.cjs')(win);
  await require('./preparo-caixa-ui.cjs')(win);
  await js("document.getElementById('pair-close').click(); document.getElementById('kitchen-open').click()");
  await js("document.querySelector('#kitchen-cards button').click()");
  await wait("document.getElementById('kitchen-cards').textContent.includes('Em preparo')");
  const kitchenOutput = path.resolve(__dirname, '../../output/etapa-4-cozinha'); fs.mkdirSync(kitchenOutput, { recursive: true });
  await new Promise(resolve => setTimeout(resolve, 500));
  fs.writeFileSync(path.join(kitchenOutput, 'cozinha-kds-cupom.png'), (await win.webContents.capturePage()).toPNG());
  await js("document.querySelector('#kitchen-print-list button').click(); document.getElementById('kitchen-reason').value = 'Segunda via conferida no teste'; document.getElementById('kitchen-reprint').requestSubmit()");
  await wait("document.querySelectorAll('#kitchen-print-list [data-status=simulado]').length === 2");
  assert.ok(await js("document.getElementById('kitchen-preview').srcdoc.includes('REIMPRESSÃO')"));
  for (const target of ['Pronto', 'Nenhum pedido']) {
    await js("document.querySelector('#kitchen-cards button').click()");
    await wait(`document.getElementById('kitchen-cards').textContent.includes(${JSON.stringify(target)})`);
  }
  await js("document.getElementById('kitchen-close').click(); document.getElementById('pair-open').click()");
  assert.equal(await js("document.getElementById('pair-issued').value"), '');
  await action("document.getElementById('pair-logout').click()");
  await action("document.getElementById('pair-recover').click()");
  assert.match(await read('pair-terminal-state'), /Terminal ativo/);
  // Confirma restauração do Auth do terminal, não só estado em memória da tela.
  await new Promise(resolve => { win.webContents.once('did-finish-load', resolve); win.webContents.reload(); });
  await js("document.getElementById('pair-open').click()");
  await action("document.getElementById('pair-recover').click()");
  assert.equal(await js("document.getElementById('pair-uid').value"), uid);
  await wait("document.querySelectorAll('#kitchen-print-list [data-status=simulado]').length === 2");
  assert.equal(await js("document.querySelectorAll('#kitchen-print-list [data-status=pendente]').length"), 0);
  await wait("document.querySelectorAll('#receive-list [data-linha-id]').length === 1");
  assert.match(await read('receive-list'), /12,50/);
  await js("document.getElementById('pair-close').click(); document.getElementById('receive-open').click()");
  await wait("document.getElementById('receive-dialog').open && !document.getElementById('pair-dialog').open");
  await new Promise(resolve => setTimeout(resolve, 500)); // aguarda composição da janela oculta antes da captura
  const receiveOutput = path.resolve(__dirname, '../../output/etapa-3-recebimento'); fs.mkdirSync(receiveOutput, { recursive: true });
  fs.writeFileSync(path.join(receiveOutput, 'recebimento-pdv.png'), (await win.webContents.capturePage()).toPNG());
  await js("document.querySelector('#receive-list [data-action=checkout]').click(); document.getElementById('checkout-cash').value='20,00'; document.getElementById('checkout-confirm').checked=true; document.getElementById('checkout-form').requestSubmit()");
  await wait("document.getElementById('checkout-dialog').dataset.busy === 'false' && document.getElementById('checkout-message').textContent.includes('Venda registrada')");
  assert.match(await read('checkout-message'), /7,50/);
  await js("document.getElementById('checkout-reconcile').click()");
  await wait("document.getElementById('checkout-reconciliation').dataset.totalCentavos === '1750'");
  assert.equal(await js("window.StorageService.getVendas().length"),1);
  const reconciliationOutput = path.resolve(__dirname, '../../output/etapa-7b'); fs.mkdirSync(reconciliationOutput, { recursive: true });
  fs.writeFileSync(path.join(reconciliationOutput,'conferencia.png'),(await win.webContents.capturePage()).toPNG());
  await wait("document.querySelectorAll('#checkout-sales [data-status=concluida]').length === 1");
  const checkoutOutput = path.resolve(__dirname, '../../output/etapa-5-fechamento'); fs.mkdirSync(checkoutOutput, { recursive: true });
  await win.webContents.capturePage(undefined, { stayHidden: true, stayAwake: true });
  await new Promise(resolve => setTimeout(resolve, 1000));
  fs.writeFileSync(path.join(checkoutOutput, 'venda-registrada.png'), (await win.webContents.capturePage(undefined, { stayHidden: true, stayAwake: true })).toPNG());
  await new Promise(resolve => { win.webContents.once('did-finish-load', resolve); win.webContents.reload(); });
  await wait("document.querySelectorAll('#checkout-sales [data-status=concluida]').length === 1");
  assert.equal(await js("document.querySelectorAll('#receive-list [data-atendimento-id]').length"), 0);
  await js("document.getElementById('checkout-open').click(); document.querySelector('#checkout-sales button').click(); document.getElementById('checkout-reason').value='Devolução conferida no teste'; document.getElementById('checkout-return').checked=true; document.getElementById('checkout-refund-confirm').checked=true; document.getElementById('checkout-adjust').requestSubmit()");
  await wait("document.querySelectorAll('#checkout-sales [data-status=estornada]').length === 1 && document.getElementById('checkout-dialog').dataset.busy === 'false'");
  await js("document.getElementById('checkout-reconcile').click()");
  await wait("document.getElementById('checkout-reconciliation').dataset.totalCentavos === '500'");
  assert.equal(await js("window.StorageService.getVendas().length"),1);
  console.log('CONCILIACAO UI PASS: R$5 locais + R$12,50 restaurante; estorno retorna total a R$5 sem importar venda.');
  await wait("document.querySelectorAll('#kitchen-print-list [data-status=simulado]').length === 3");
  await wait("document.getElementById('kitchen-alerts').textContent.includes('estorno')");
  await js("document.getElementById('server-turn-refresh').click()");
  await wait("document.getElementById('checkout-dialog').dataset.busy === 'false' && document.getElementById('server-turn-state').dataset.status === 'aberto'");
  await js("document.getElementById('server-turn-count').value='0,00';document.getElementById('server-turn-confirm').checked=true;document.getElementById('server-turn-close-form').requestSubmit()");
  await wait("document.getElementById('server-turn-state').dataset.status === 'fechado'");
  const turnOutput = path.resolve(__dirname,'../../output/etapa-7c'); fs.mkdirSync(turnOutput,{recursive:true});
  await js("document.getElementById('server-turn-state').scrollIntoView({block:'center'})");
  await new Promise(r=>setTimeout(r,600));
  fs.writeFileSync(path.join(turnOutput,'turno-encerrado.png'),(await win.webContents.capturePage()).toPNG());
  console.log('TURNO UI PASS: sem ativacao legada, abertura no servidor, pagamento, estorno e encerramento.');
  await js("document.getElementById('server-turn-integrate').click()");
  await wait("document.getElementById('server-turn-integrated').dataset.totalCentavos === '500'");
  await js("document.getElementById('server-turn-integrate').click()");
  await wait("document.getElementById('checkout-dialog').dataset.busy === 'false'");
  assert.equal(await js("window.StorageService.getVendas().length"),1);
  assert.equal(await js("window.CaixaModule.calcularResumoFinanceiro(window.StorageService.getTurnoAtual()).vendasCount"),2);
  await js("document.getElementById('server-turn-integrated').scrollIntoView({block:'center'})");
  const integrationOutput=path.resolve(__dirname,'../../output/etapa-7d');fs.mkdirSync(integrationOutput,{recursive:true});
  await new Promise(r=>setTimeout(r,600));fs.writeFileSync(path.join(integrationOutput,'resumo-incorporado.png'),(await win.webContents.capturePage()).toPNG());
  console.log('CAIXA INTEGRADO UI PASS: resumo no calculador antigo, aplicação repetida sem duplicar, uma venda local preservada.');
  assert.equal(await js("document.querySelectorAll('#server-turn-items [data-movimento]').length"),2);
  assert.match(await read('server-turn-items'),/Bacon/);
  assert.match(await read('server-turn-items'),/Estorno.*-1/);
  await js("document.getElementById('server-turn-items').scrollIntoView({block:'center'})");
  await new Promise(r=>setTimeout(r,2500));
  const detailOutput=path.resolve(__dirname,'../../output/etapa-7e');fs.mkdirSync(detailOutput,{recursive:true});
  fs.writeFileSync(path.join(detailOutput,'itens-restaurante.png'),(await win.webContents.capturePage()).toPNG());
  console.log('ITENS UI PASS: recebimento e estorno com Bacon, sem duplicar itens.');
  await fill({'cycle-count':'4,00'});
  await js("document.getElementById('cycle-close-confirm').checked=true;document.getElementById('cycle-close-form').requestSubmit()");
  await wait("document.getElementById('cycle-state').dataset.status === 'sem_turno' && document.getElementById('checkout-dialog').dataset.busy === 'false'");
  assert.equal(await js("window.StorageService.getHistoricoTurnos().length"),1);
  assert.equal(await js("window.StorageService.getHistoricoTurnos()[0].diferenca"),-1);
  await win.webContents.reload();
  await wait("!!document.getElementById('cycle-state') && document.getElementById('checkout-dialog').dataset.busy === 'false'");
  await js("document.getElementById('checkout-open').click()");
  assert.equal(await js("document.getElementById('cycle-state').dataset.status"),'sem_turno');
  await fill({'cycle-fund':'10,00'});
  await js("document.getElementById('cycle-open-confirm').checked=true;document.getElementById('cycle-open-form').requestSubmit()");
  await wait("document.getElementById('cycle-state').dataset.status === 'aberto' && document.getElementById('checkout-dialog').dataset.busy === 'false'");
  const nextTurnId=await js("window.StorageService.getTurnoAtual().id");assert.notEqual(nextTurnId,'TRN-DEMO-ATUAL');
  await win.webContents.reload();
  await wait("!!document.getElementById('cycle-state') && document.getElementById('checkout-dialog').dataset.busy === 'false'");
  await js("document.getElementById('checkout-open').click();document.getElementById('server-turn-refresh').click()");
  await wait("document.getElementById('server-turn-state').dataset.status === 'aberto' && document.getElementById('checkout-dialog').dataset.busy === 'false'");
  assert.equal(await js("window.StorageService.getTurnoAtual().id"),nextTurnId);
  await js("document.getElementById('checkout-reconcile').click()");
  await wait("document.getElementById('checkout-reconciliation').dataset.totalCentavos === '0' && document.getElementById('checkout-dialog').dataset.busy === 'false'");
  assert.equal(await js("window.StorageService.getVendas().length"),1);
  assert.equal(await js("window.CaixaModule.calcularResumoFinanceiro(window.StorageService.getHistoricoTurnos()[0]).totalVendas"),5);
  await js("document.getElementById('cycle-title').scrollIntoView({block:'center'})");
  await new Promise(r=>setTimeout(r,2500));
  const cycleOutput=path.resolve(__dirname,'../../output/etapa-7f');fs.mkdirSync(cycleOutput,{recursive:true});
  fs.writeFileSync(path.join(cycleOutput,'novo-turno-historico.png'),(await win.webContents.capturePage()).toPNG());
  console.log('CICLO UI PASS: caixa arquivado com diferença, recarga, próximo turno com fundo próprio e total zerado, histórico preservado.');
  await js("document.getElementById('local-stock-title').scrollIntoView({block:'center'})");
  await fill({'local-stock-product':'farinha-legado-teste','local-stock-quantity':'250'});
  await js("document.getElementById('local-cart-add').click()");await wait("document.getElementById('checkout-dialog').dataset.busy === 'false'");
  await js("document.getElementById('local-stock-preview').click()");
  await wait("document.getElementById('checkout-dialog').dataset.busy === 'false'");
  assert.match(await read('local-stock-preview-text'),/5,00/);
  await js("document.getElementById('local-stock-confirm').checked=true;document.getElementById('local-stock-form').requestSubmit()");
  await wait("!!document.getElementById('local-stock-state').dataset.vendaId && document.getElementById('checkout-dialog').dataset.busy === 'false'",60000);
  assert.equal(await js("window.StorageService.getVendas().length"),2);
  assert.equal(await js("window.StorageService.getProdutos().find(p=>p.id==='farinha-legado-teste').estoque"),2500);
  assert.equal(await js("window.StorageService.getMovimentosEstoque().length"),0);
  await js("document.getElementById('checkout-reconcile').click()");
  await wait("document.getElementById('checkout-reconciliation').dataset.totalCentavos === '500' && document.getElementById('checkout-dialog').dataset.busy === 'false'");
  await js("document.getElementById('local-stock-state').scrollIntoView({block:'center'})");await new Promise(r=>setTimeout(r,2500));
  const bridgeOutput=path.resolve(__dirname,'../../output/etapa-7h');fs.mkdirSync(bridgeOutput,{recursive:true});fs.writeFileSync(path.join(bridgeOutput,'venda-local-estoque-servidor.png'),(await win.webContents.capturePage()).toPNG());
  await win.webContents.reload();await wait("!!document.getElementById('local-stock-state') && document.getElementById('checkout-dialog').dataset.busy === 'false'");
  await js("document.getElementById('checkout-open').click()");
  assert.equal(await js("window.StorageService.getVendas().length"),2);assert.equal(await js("localStorage.getItem('flowpdv_venda_servidor_pendente')"),null);
  console.log('PONTE ESTOQUE UI PASS: venda local de 250 g por R$5, estoque remoto único, caixa local uma vez e recarga sem pendência.');

  // Primeiro uma recusa sem baixa; depois falha simulada após baixa, antes da gravação local.
  for(const quantity of ['99999','250']){
    await wait("document.getElementById('checkout-dialog').dataset.rascunhoReady === 'true'");
    await fill({'local-stock-product':'farinha-legado-teste','local-stock-quantity':quantity});
    await js("document.getElementById('local-cart-add').click()");await wait("document.getElementById('checkout-dialog').dataset.busy === 'false'");
    await js("document.getElementById('local-stock-preview').click()");await wait("document.getElementById('checkout-dialog').dataset.busy === 'false'");
    if(quantity==='250')await js("window.salvarVendaOriginalTeste=window.StorageService.saveVendaComEstoqueServidorTeste;window.StorageService.saveVendaComEstoqueServidorTeste=()=>{throw new Error('Falha simulada antes da gravação local')};void 0");
    await js("document.getElementById('local-stock-confirm').checked=true;document.getElementById('local-stock-form').requestSubmit()");
    await wait("!document.getElementById('local-stock-cancel-form').hidden && document.getElementById('checkout-dialog').dataset.busy === 'false'",60000);
    if(quantity==='250')await js("window.StorageService.saveVendaComEstoqueServidorTeste=window.salvarVendaOriginalTeste;void 0");
    const pendingId=await js("JSON.parse(localStorage.getItem('flowpdv_venda_servidor_pendente')).venda.id");
    if(quantity==='250') {
      await setHomologacao('suspensa');
      assert.equal(await js("document.getElementById('local-stock-resume').disabled"),false);
      assert.equal(await js("document.getElementById('classic-pdv-barcode-input').disabled"),true);
      assert.equal(await js("document.getElementById('op-add').disabled"),true);
    }
    await js("document.getElementById('checkout-close').click()");await wait("!document.getElementById('checkout-dialog').open");
    await js("document.getElementById('op-open').click();document.getElementById('op-pay').click()");
    assert.equal(await js("document.activeElement.id"),'local-stock-state');
    await js("document.getElementById('checkout-dialog').dispatchEvent(new KeyboardEvent('keydown',{key:'F4',bubbles:true}))");
    assert.equal(await js("JSON.parse(localStorage.getItem('flowpdv_venda_servidor_pendente')).venda.id"),pendingId);
    assert.equal(await js("document.getElementById('local-stock-form').hidden"),true);

    await win.webContents.reload();await wait("!!document.getElementById('local-stock-cancel-form') && !document.getElementById('local-stock-cancel-form').hidden && document.getElementById('checkout-dialog').dataset.busy === 'false'");
    await js("document.getElementById('checkout-open').click()");
    await fill({'local-stock-cancel-reason':'Cliente desistiu no teste de cancelamento'});
    await js("document.getElementById('local-stock-cancel-confirm').checked=true;document.getElementById('local-stock-cancel-form').requestSubmit()");
    await wait(`document.getElementById('local-stock-state').dataset.canceladaId === ${JSON.stringify(pendingId)} && document.getElementById('checkout-dialog').dataset.busy === 'false'`,60000);
    assert.equal(await js("window.StorageService.getVendas().length"),2);assert.equal(await js("localStorage.getItem('flowpdv_venda_servidor_pendente')"),null);
    assert.equal(await js("window.StorageService.getMovimentosEstoque().length"),0);
    if(quantity==='250') {
      assert.equal(await js("document.getElementById('checkout-dialog').dataset.novasPermitidas"),'false');
      await setHomologacao('habilitada');
      console.log('SUSPENSAO CANCELAMENTO UI PASS: baixa pendente, suspensão, recarga, cancelamento e reativação sem venda extra.');
    }
  }
  await js("document.getElementById('checkout-reconcile').click()");
  await wait("document.getElementById('checkout-reconciliation').dataset.totalCentavos === '500' && document.getElementById('checkout-dialog').dataset.busy === 'false'");
  const cancelOutput=path.resolve(__dirname,'../../output/etapa-7i');fs.mkdirSync(cancelOutput,{recursive:true});
  await js("document.getElementById('local-stock-state').scrollIntoView({block:'center'})");
  fs.writeFileSync(path.join(cancelOutput,'tentativa-cancelada.png'),(await win.webContents.capturePage(undefined,{stayHidden:true,stayAwake:true})).toPNG());
  console.log('CANCELAMENTO LOCAL UI PASS: recusa sem baixa e falha após baixa, recarga, cancelamento pelo formulário, caixa R$5 preservado.');

  const refundSaleId=await js("window.StorageService.getVendas().find(v=>v.estoqueServidorV2).id");
  await js("document.getElementById('server-turn-refresh').click()");await wait("document.getElementById('checkout-dialog').dataset.busy === 'false'");
  await fill({'server-turn-count':'10,00'});await js("document.getElementById('server-turn-confirm').checked=true;document.getElementById('server-turn-close-form').requestSubmit()");
  await wait("document.getElementById('server-turn-state').dataset.status === 'fechado' && document.getElementById('checkout-dialog').dataset.busy === 'false'");
  await js("document.getElementById('server-turn-integrate').click()");await wait("document.getElementById('checkout-dialog').dataset.busy === 'false'");
  await fill({'cycle-count':'15,00'});await js("document.getElementById('cycle-close-confirm').checked=true;document.getElementById('cycle-close-form').requestSubmit()");
  await wait("document.getElementById('cycle-state').dataset.status === 'sem_turno' && document.getElementById('checkout-dialog').dataset.busy === 'false'");
  const beforeRefundHistory=await js("JSON.stringify(window.StorageService.getHistoricoTurnos())");
  await fill({'cycle-fund':'10,00'});await js("document.getElementById('cycle-open-confirm').checked=true;document.getElementById('cycle-open-form').requestSubmit()");
  await wait("document.getElementById('cycle-state').dataset.status === 'aberto' && document.getElementById('checkout-dialog').dataset.busy === 'false'");
  await fill({'local-refund-sale':refundSaleId,'local-refund-reason':'Devolução integral em turno posterior'});
  await js("document.getElementById('local-refund-stock').checked=true;document.getElementById('local-refund-confirm').checked=true;document.getElementById('local-refund-form').requestSubmit()");
  await wait(`document.getElementById('local-refund-state').dataset.vendaId === ${JSON.stringify(refundSaleId)} && document.getElementById('checkout-dialog').dataset.busy === 'false'`,60000);
  assert.equal(await js("JSON.stringify(window.StorageService.getHistoricoTurnos())"),beforeRefundHistory);
  assert.equal(await js("window.StorageService.getVendas().length"),2);
  await win.webContents.reload();await wait("!!document.getElementById('local-refund-state') && document.getElementById('checkout-dialog').dataset.busy === 'false'");
  await js("document.getElementById('checkout-open').click();document.getElementById('checkout-reconcile').click()");
  await wait("document.getElementById('checkout-reconciliation').dataset.totalCentavos === '-500' && document.getElementById('checkout-dialog').dataset.busy === 'false'");
  assert.equal(await js("window.StorageService.getTurnoAtual().estornosLocaisV2.length"),1);
  assert.equal(await js("localStorage.getItem('flowpdv_estorno_local_pendente')"),null);
  assert.equal(await js("window.CaixaModule.calcularResumoFinanceiro(window.StorageService.getHistoricoTurnos()[0]).totalVendas"),5);
  assert.equal(await js("window.CaixaModule.calcularResumoFinanceiro(window.StorageService.getTurnoAtual()).totalVendas"),-5);
  await js("document.getElementById('local-refund-title').scrollIntoView({block:'start'})");
  const refundOutput=path.resolve(__dirname,'../../output/etapa-7j');fs.mkdirSync(refundOutput,{recursive:true});
  fs.writeFileSync(path.join(refundOutput,'estorno-local.png'),(await win.webContents.capturePage(undefined,{stayHidden:true,stayAwake:true})).toPNG());
  console.log('ESTORNO LOCAL UI PASS: venda em turno encerrado, devolução no turno seguinte, caixa -R$5, histórico preservado e recarga sem ajuste duplicado.');

  await wait("document.getElementById('checkout-dialog').dataset.rascunhoReady === 'true'");

  await js("document.getElementById('checkout-close').click();document.getElementById('op-open').click()");
  await fill({'op-search':'farinha-legado-teste','op-quantity':'50'});await js("document.getElementById('op-search').dispatchEvent(new Event('input'));document.getElementById('op-search').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}))");await wait("document.getElementById('checkout-dialog').dataset.busy === 'false'");
  await js("document.getElementById('op-search').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}))");await wait("document.getElementById('checkout-dialog').dataset.busy === 'false'");assert.equal(await js("document.querySelector('#pdv-itens-tbody input').value"),'100');
  await fill({'op-search':'Açúcar','op-quantity':'0,25'});await js("document.getElementById('op-search').dispatchEvent(new Event('input'));document.getElementById('op-add').click()");await wait("document.getElementById('checkout-dialog').dataset.busy === 'false'");
  assert.equal(await js("document.querySelectorAll('#pdv-itens-tbody input').length"),2);assert.match(await read('pdv-total-display'),/4,00/);
  await js("document.querySelectorAll('#pdv-itens-tbody button')[1].click()");await wait("document.getElementById('checkout-dialog').dataset.busy === 'false'");assert.equal(await js("document.querySelectorAll('#pdv-itens-tbody input').length"),1);
  await js("document.getElementById('op-add').click()");await wait("document.getElementById('checkout-dialog').dataset.busy === 'false'");
  const opOutput=path.resolve(__dirname,'../../output/etapa-7p');fs.mkdirSync(opOutput,{recursive:true});const oldSize=win.getSize();
  for(const width of [1366,1024]){
    win.setSize(width,768);await js("document.getElementById('pdv-operacional-teste').scrollIntoView({block:'start',behavior:'instant'});new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))");await new Promise(r=>setTimeout(r,300));
    fs.writeFileSync(path.join(opOutput,'balcao-'+width+'.png'),(await win.webContents.capturePage(undefined,{stayHidden:true,stayAwake:true})).toPNG());
    const geometry=await js("(()=>{const h=document.getElementById('pdv-operacional-teste'),b=document.getElementById('op-pay'),r=b.getBoundingClientRect();return {overflow:h.scrollWidth>h.clientWidth+1,button:{x:r.x,y:r.y,w:r.width,h:r.height},viewport:{w:innerWidth,h:innerHeight},hit:document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)?.outerHTML.slice(0,300)};})()");console.log('BALCAO GEOMETRY',width,JSON.stringify(geometry));assert.equal(geometry.overflow,false);
  }win.setSize(...oldSize);


  const beforeOffline=await js("document.querySelectorAll('#pdv-itens-tbody tr').length");
  const probeNetwork = "fetch('http://127.0.0.1:9099/',{mode:'no-cors',cache:'no-store'}).then(()=>true,()=>false)";
  assert.equal(await js(probeNetwork), true, 'emulador acessível antes da interrupção');
  let redeInterrompida = true;
  const { testUrlAllowed } = require('../runtime-profile.cjs');
  // Interrompe requisições no transporte do Electron, mantendo a mesma barreira
  // contra rede externa do perfil de teste. Não altera a rede do computador.
  win.webContents.session.webRequest.onBeforeRequest((details, callback) => {
    callback({ cancel: !testUrlAllowed(details.url) || (redeInterrompida && /^https?:/.test(details.url)) });
  });
  await win.webContents.session.closeAllConnections();
  assert.equal(await js(probeNetwork), false, 'rede da sessão Electron realmente interrompida');
  await js("window.dispatchEvent(new Event('offline'))");
  assert.equal(await js("document.getElementById('op-add').disabled"),true);
  assert.equal(await js("document.getElementById('classic-pdv-barcode-input').disabled"),true);
  assert.equal(await js("document.getElementById('op-pay').disabled"),false);
  assert.equal(await js("document.querySelectorAll('#pdv-itens-tbody tr').length"),beforeOffline);
  const accessOutput=path.resolve(__dirname,'../../output/etapa-7x');fs.mkdirSync(accessOutput,{recursive:true});
  fs.writeFileSync(path.join(accessOutput,'moderno-sem-conexao.png'),(await win.webContents.capturePage(undefined,{stayHidden:true,stayAwake:true})).toPNG());
  await js("document.getElementById('op-classic-open').click();new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))");
  fs.writeFileSync(path.join(accessOutput,'classico-sem-conexao.png'),(await win.webContents.capturePage(undefined,{stayHidden:true,stayAwake:true})).toPNG());
  redeInterrompida = false;
  assert.equal(await js(probeNetwork), true, 'rede restaurada antes de revalidar');
  await js("document.querySelector('#classic-pdv-shell .classic-window-controls span').click();document.getElementById('op-open').click();window.dispatchEvent(new Event('online'))");
  await wait("document.getElementById('checkout-dialog').dataset.novasPermitidas === 'true'");
  assert.equal(await js("document.getElementById('classic-pdv-barcode-input').disabled"),false);
  console.log('ACESSO OPERACIONAL UI PASS: suspensão/reativação ao vivo e desconexão preservando carrinho e acesso ao pagamento.');
  console.log('REDE INTERROMPIDA UI PASS: requisição real falhou offline, retornou online e nova autorização preservou o carrinho.');
  await js("document.getElementById('op-pay').click()");assert.equal(await js("document.getElementById('checkout-dialog').dataset.origem"),'moderno');
  await js("document.getElementById('checkout-close').click()");await wait("document.activeElement.id === 'op-search'");
  await js("document.getElementById('op-classic-open').click()");assert.equal(await js("document.querySelectorAll('#classic-pdv-itens-tbody tr').length"),2);assert.match(await read('classic-total-venda'),/4,00/);
  await fill({'classic-pdv-barcode-input':'50*farinha-legado-teste'});await js("document.getElementById('classic-pdv-barcode-input').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}))");await wait("document.getElementById('checkout-dialog').dataset.busy === 'false'");assert.match(await read('classic-total-venda'),/5,00/);
  assert.equal(await js("(()=>{const row=document.querySelector('#classic-pdv-itens-tbody tr[data-produto-id=farinha-legado-teste]');row.click();const focused=document.activeElement===row && row.isConnected;row.dispatchEvent(new MouseEvent('dblclick',{bubbles:true}));return focused;})()"),true);await fill({'classic-test-quantity':'100'});await js("document.querySelector('#classic-test-search form').requestSubmit()");await wait("!document.getElementById('classic-test-search').open && document.getElementById('checkout-dialog').dataset.busy === 'false'");assert.match(await read('classic-total-venda'),/4,00/);
  await js("document.querySelector('#classic-pdv-itens-tbody tr[data-produto-id=acucar-legado-teste]').click();document.activeElement.dispatchEvent(new KeyboardEvent('keydown',{key:'Delete',bubbles:true}))");await wait("document.getElementById('checkout-dialog').dataset.busy === 'false'");assert.equal(await js("document.querySelectorAll('#classic-pdv-itens-tbody tr').length"),1);
  await js("document.getElementById('classic-pdv-shell').dispatchEvent(new KeyboardEvent('keydown',{key:'F2',bubbles:true}))");await fill({'classic-test-query':'Açúcar','classic-test-quantity':'0,25'});await js("document.getElementById('classic-test-query').dispatchEvent(new Event('input'));document.querySelector('#classic-test-search form').requestSubmit()");await wait("!document.getElementById('classic-test-search').open && document.getElementById('checkout-dialog').dataset.busy === 'false'");assert.match(await read('classic-total-venda'),/4,00/);
  await fill({'classic-pdv-barcode-input':'-2*farinha-legado-teste'});await js("document.getElementById('classic-pdv-barcode-input').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}))");assert.match(await read('classic-test-notice'),/positiva/);assert.match(await read('classic-total-venda'),/4,00/);
  const classicOutput=path.resolve(__dirname,'../../output/etapa-7q');fs.mkdirSync(classicOutput,{recursive:true});
  for(const width of [1366,1024]){win.setSize(width,768);await js("document.getElementById('classic-pdv-barcode-input').value='';new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))");await new Promise(r=>setTimeout(r,250));fs.writeFileSync(path.join(classicOutput,'classico-'+width+'.png'),(await win.webContents.capturePage(undefined,{stayHidden:true,stayAwake:true})).toPNG());assert.equal(await js("document.getElementById('classic-pdv-shell').scrollWidth<=document.getElementById('classic-pdv-shell').clientWidth+1"),true);}win.setSize(...oldSize);
  await js("document.getElementById('classic-pdv-shell').dispatchEvent(new KeyboardEvent('keydown',{key:'F4',bubbles:true}))");
  assert.equal(await js("document.getElementById('checkout-dialog').dataset.origem"),'classico');
  assert.equal(await js("getComputedStyle(document.querySelector('[aria-labelledby=local-refund-title]')).display"),'none');
  await js("document.getElementById('checkout-dialog').dispatchEvent(new KeyboardEvent('keydown',{key:'F4',bubbles:true}))");await wait("document.getElementById('checkout-dialog').dataset.busy === 'false'");
  assert.equal(await js("window.StorageService.getVendas().length"),2);
  const paymentOutput=path.resolve(__dirname,'../../output/etapa-7r');fs.mkdirSync(paymentOutput,{recursive:true});
  for(const width of [1366,1024]){win.setSize(width,768);await js("document.getElementById('checkout-dialog').scrollTop=0;new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))");fs.writeFileSync(path.join(paymentOutput,'conferencia-'+width+'.png'),(await win.webContents.capturePage(undefined,{stayHidden:true,stayAwake:true})).toPNG());assert.equal(await js("document.getElementById('checkout-dialog').scrollWidth<=document.getElementById('checkout-dialog').clientWidth+1"),true);}win.setSize(...oldSize);
  win.webContents.sendInputEvent({type:'keyDown',keyCode:'Escape'});win.webContents.sendInputEvent({type:'keyUp',keyCode:'Escape'});await wait("!document.getElementById('checkout-dialog').open && document.activeElement.id === 'classic-pdv-barcode-input'");
  await js("document.getElementById('classic-pdv-shell').dispatchEvent(new KeyboardEvent('keydown',{key:'F8',bubbles:true}))");assert.equal(await js("document.activeElement.id"),'local-discount');
  await js("document.getElementById('checkout-close').click()");await wait("document.activeElement.id === 'classic-pdv-barcode-input'");
  await js("document.getElementById('classic-pdv-shell').dispatchEvent(new KeyboardEvent('keydown',{key:'F4',bubbles:true}))");
  console.log('CONFERENCIA UI PASS: contexto moderno/clássico, retorno de foco, ESC, F8, F4 sem registro e pendência original preservada.');
  console.log('CLASSICO UI PASS: layout original, carrinho compartilhado, leitor, F2, edição, DEL e F4 sem baixa duplicada.');
assert.equal(await js("document.getElementById('checkout-dialog').open"),true);console.log('BALCAO UI PASS: busca, código, quantidades, remoção, total, F4 e controles livres nas duas resoluções.');
  await js("document.getElementById('local-stock-preview').click()");await wait("document.getElementById('checkout-dialog').dataset.busy === 'false'");
  await js("document.getElementById('local-stock-confirm').checked=true;const i=document.querySelector('#local-cart-items [data-produto-id=farinha-legado-teste] input');i.value='250';i.dispatchEvent(new Event('input',{bubbles:true}))");
  assert.equal(await js("document.getElementById('local-stock-confirm').checked"),false);
  await js("document.getElementById('local-stock-preview').click()");await wait("document.getElementById('checkout-dialog').dataset.busy === 'false'");
  assert.match(await read('local-stock-preview-text'),/7,00/);
  const cartOutput=path.resolve(__dirname,'../../output/etapa-7k');fs.mkdirSync(cartOutput,{recursive:true});
  await js("document.getElementById('local-cart-items').scrollIntoView({block:'start'})");
  fs.writeFileSync(path.join(cartOutput,'carrinho-conferido.png'),(await win.webContents.capturePage(undefined,{stayHidden:true,stayAwake:true})).toPNG());
  // Um preço alterado depois da conferência exige nova revisão, sem enviar uma venda.
  await js("window.StorageService.getProdutos().find(p=>p.id==='acucar-legado-teste').preco=9;document.getElementById('local-stock-confirm').checked=true;document.getElementById('local-stock-form').requestSubmit()");
  await wait("document.getElementById('checkout-dialog').dataset.busy === 'false'");assert.match(await read('checkout-message'),/mudaram/);
  assert.equal(await js("localStorage.getItem('flowpdv_venda_servidor_pendente')"),null);
  await js("window.StorageService.getProdutos().find(p=>p.id==='acucar-legado-teste').preco=8;document.getElementById('local-stock-preview').click()");await wait("document.getElementById('checkout-dialog').dataset.busy === 'false'");
  await fill({'local-stock-cash':'6,99'});await js("document.getElementById('local-stock-cash').dispatchEvent(new Event('input'));document.getElementById('local-stock-preview').click()");await wait("document.getElementById('checkout-dialog').dataset.busy === 'false'");
  assert.match(await read('checkout-message'),/menor que o total/);assert.equal(await js("localStorage.getItem('flowpdv_venda_servidor_pendente')"),null);
  await fill({'local-stock-cash':'10,00'});await js("document.getElementById('local-stock-cash').dispatchEvent(new Event('input'));document.getElementById('local-stock-preview').click()");await wait("document.getElementById('checkout-dialog').dataset.busy === 'false'");
  assert.match(await read('local-stock-preview-text'),/Recebido:.*10,00.*Troco:.*3,00/);
  await js("document.getElementById('local-stock-confirm').checked=true;document.getElementById('local-stock-cash').value='20,00';document.getElementById('local-stock-form').requestSubmit()");await wait("document.getElementById('checkout-dialog').dataset.busy === 'false'");
  assert.match(await read('checkout-message'),/mudaram/);assert.equal(await js("localStorage.getItem('flowpdv_venda_servidor_pendente')"),null);
  await fill({'local-stock-cash':'10,00'});await js("document.getElementById('local-stock-cash').dispatchEvent(new Event('input'));document.getElementById('local-stock-preview').click()");await wait("document.getElementById('checkout-dialog').dataset.busy === 'false'");
  const cashOutput=path.resolve(__dirname,'../../output/etapa-7l');fs.mkdirSync(cashOutput,{recursive:true});
  await js("document.getElementById('local-stock-cash').scrollIntoView({block:'center',behavior:'instant'})");
  fs.writeFileSync(path.join(cashOutput,'troco-conferido.png'),(await win.webContents.capturePage(undefined,{stayHidden:true,stayAwake:true})).toPNG());
  await fill({'local-pay-pix':'8'});await js("document.getElementById('local-pay-pix').dispatchEvent(new Event('input'));document.getElementById('local-stock-preview').click()");await wait("document.getElementById('checkout-dialog').dataset.busy === 'false'");assert.match(await read('checkout-message'),/excedem/);
  await fill({'local-pay-pix':'2','local-pay-debit':'1','local-pay-credit':'2'});await js("document.getElementById('local-pay-pix').dispatchEvent(new Event('input'));document.getElementById('local-stock-preview').click()");await wait("document.getElementById('checkout-dialog').dataset.busy === 'false'");assert.match(await read('local-stock-preview-text'),/Dinheiro:.*2,00.*PIX:.*2,00.*Débito:.*1,00.*Crédito:.*2,00.*Troco:.*8,00/);
  await js("document.getElementById('local-stock-confirm').checked=true;document.getElementById('local-pay-pix').value='1';document.getElementById('local-stock-form').requestSubmit()");await wait("document.getElementById('checkout-dialog').dataset.busy === 'false'");assert.match(await read('checkout-message'),/mudaram/);assert.equal(await js("localStorage.getItem('flowpdv_venda_servidor_pendente')"),null);
  await fill({'local-pay-pix':'2'});await js("document.getElementById('local-pay-pix').dispatchEvent(new Event('input'));document.getElementById('local-stock-preview').click()");await wait("document.getElementById('checkout-dialog').dataset.busy === 'false'");
  const splitOutput=path.resolve(__dirname,'../../output/etapa-7m');fs.mkdirSync(splitOutput,{recursive:true});
  await js("document.getElementById('local-stock-cash').scrollIntoView({block:'center',behavior:'instant'})");fs.writeFileSync(path.join(splitOutput,'pagamento-dividido.png'),(await win.webContents.capturePage(undefined,{stayHidden:true,stayAwake:true})).toPNG());
  await fill({'local-discount':'7,01','local-adjust-reason':'Acordo comercial'});await js("document.getElementById('local-discount').dispatchEvent(new Event('input'));document.getElementById('local-stock-preview').click()");await wait("document.getElementById('checkout-dialog').dataset.busy === 'false'");assert.match(await read('checkout-message'),/desconto não pode superar/i);
  await fill({'local-discount':'0,50','local-surcharge':'1,50'});await js("document.getElementById('local-discount').dispatchEvent(new Event('input'));document.getElementById('local-stock-preview').click()");await wait("document.getElementById('checkout-dialog').dataset.busy === 'false'");assert.match(await read('local-stock-preview-text'),/Subtotal:.*7,00.*Desconto:.*0,50.*Acréscimo:.*1,50.*Total:.*8,00/);
  await js("document.getElementById('local-stock-confirm').checked=true;document.getElementById('local-adjust-reason').value='Outro motivo';document.getElementById('local-stock-form').requestSubmit()");await wait("document.getElementById('checkout-dialog').dataset.busy === 'false'");assert.match(await read('checkout-message'),/mudaram/);assert.equal(await js("localStorage.getItem('flowpdv_venda_servidor_pendente')"),null);
  await fill({'local-adjust-reason':'Acordo comercial'});await js("document.getElementById('local-adjust-reason').dispatchEvent(new Event('input'));document.getElementById('local-stock-preview').click()");await wait("document.getElementById('checkout-dialog').dataset.busy === 'false'");
  const adjustOutput=path.resolve(__dirname,'../../output/etapa-7n');fs.mkdirSync(adjustOutput,{recursive:true});await js("document.getElementById('local-stock-preview-text').scrollIntoView({block:'center',behavior:'instant'})");fs.writeFileSync(path.join(adjustOutput,'ajuste-conferido.png'),(await win.webContents.capturePage(undefined,{stayHidden:true,stayAwake:true})).toPNG());
  await win.webContents.reload();await wait("document.getElementById('local-draft-state')?.textContent.includes('recuperado') && document.getElementById('checkout-dialog').dataset.busy === 'false' && document.getElementById('checkout-dialog').dataset.novasPermitidas === 'true'");await js("document.getElementById('checkout-open').click()");
  await js("document.getElementById('checkout-close').click();document.getElementById('op-classic-open').click()");assert.match(await read('classic-total-venda'),/8,00/);assert.equal(await js("document.querySelectorAll('#classic-pdv-itens-tbody tr').length"),2);await js("document.getElementById('classic-pdv-shell').dispatchEvent(new KeyboardEvent('keydown',{key:'F4',bubbles:true}))");
  assert.equal(await js("document.querySelectorAll('#local-cart-items [data-produto-id]').length"),2);assert.equal(await js("document.getElementById('local-discount').value"),'0,50');assert.equal(await js("document.getElementById('local-pay-pix').value"),'2');assert.equal(await js("document.getElementById('local-adjust-reason').value"),'Acordo comercial');assert.equal(await js("document.getElementById('local-stock-confirm').checked"),false);assert.equal(await read('local-stock-preview-text'),'');
  await js("document.getElementById('local-stock-confirm').checked=true;document.getElementById('local-stock-form').requestSubmit()");await wait("document.getElementById('checkout-dialog').dataset.busy === 'false'");assert.match(await read('checkout-message'),/Confira novamente/);assert.equal(await js("localStorage.getItem('flowpdv_venda_servidor_pendente')"),null);
  await js("document.getElementById('local-stock-preview').click()");await wait("document.getElementById('checkout-dialog').dataset.busy === 'false'");assert.match(await read('local-stock-preview-text'),/Total:.*8,00/);
  const draftOutput=path.resolve(__dirname,'../../output/etapa-7o');fs.mkdirSync(draftOutput,{recursive:true});await js("document.getElementById('checkout-open').click();document.getElementById('local-draft-state').scrollIntoView({block:'center',behavior:'instant'});new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))");await new Promise(r=>setTimeout(r,300));fs.writeFileSync(path.join(draftOutput,'rascunho-recuperado.png'),(await win.webContents.capturePage(undefined,{stayHidden:true,stayAwake:true})).toPNG());



  await js("window.salvarVendaOriginalTeste=window.StorageService.saveVendaComEstoqueServidorTeste;window.StorageService.saveVendaComEstoqueServidorTeste=()=>{throw new Error('Falha simulada antes da gravação local')};document.getElementById('local-stock-confirm').checked=true;document.getElementById('local-stock-form').requestSubmit()");
  await wait("!!localStorage.getItem('flowpdv_venda_servidor_pendente') && document.getElementById('checkout-dialog').dataset.busy === 'false'");
  const originalPending=await js("JSON.parse(localStorage.getItem('flowpdv_venda_servidor_pendente')).venda.id");
  assert.equal(await js("window.StorageService.getVendas().length"),2);
  await setHomologacao('suspensa');
  await win.webContents.reload();await wait("document.getElementById('checkout-dialog')?.dataset.novasPermitidas === 'false' && document.getElementById('checkout-dialog').dataset.busy === 'false' && !document.getElementById('local-stock-resume').hidden");
  await js("document.getElementById('op-classic-open').click();document.getElementById('classic-pdv-shell').dispatchEvent(new KeyboardEvent('keydown',{key:'F4',bubbles:true}))");
  assert.equal(await js("document.activeElement.id"),'local-stock-state');
  assert.equal(await js("JSON.parse(localStorage.getItem('flowpdv_venda_servidor_pendente')).venda.id"),originalPending);
  assert.equal(await js("document.getElementById('local-stock-form').hidden"),true);
  assert.equal(await js("document.getElementById('local-stock-resume').disabled"),false);
  await js("document.getElementById('local-stock-resume').click()");
  await wait("window.StorageService.getVendas().length === 3 && document.getElementById('checkout-dialog').dataset.busy === 'false'",60000);
  assert.equal(await js("window.StorageService.getVendas().filter(v=>v.id === "+JSON.stringify(originalPending)+").length"),1);
  await js("document.getElementById('local-stock-resume').click()");await wait("document.getElementById('checkout-dialog').dataset.busy === 'false'");
  assert.equal(await js("window.StorageService.getVendas().length"),3);
  await setHomologacao('habilitada');
  console.log('SUSPENSAO RETOMADA UI PASS: recibo original recuperado após recarga, venda única, reenvio sem duplicação e reativação.');
  assert.equal(await js("window.StorageService.getVendas()[0].itens.length"),2);assert.equal(await js("window.StorageService.getVendas()[0].total"),8);
  assert.equal(await js("document.querySelectorAll('#local-cart-items [data-produto-id]').length"),0);
  await win.webContents.reload();await wait("!!document.getElementById('local-stock-state') && document.getElementById('checkout-dialog').dataset.busy === 'false'");
  await js("document.getElementById('checkout-open').click();document.getElementById('checkout-reconcile').click()");
  await wait("document.getElementById('checkout-reconciliation').dataset.totalCentavos === '300' && document.getElementById('checkout-dialog').dataset.busy === 'false'");
  assert.equal(await js("window.StorageService.getVendas().length"),3);assert.equal(await js("localStorage.getItem('flowpdv_venda_servidor_pendente')"),null);
  assert.equal(await js("window.StorageService.getMovimentosEstoque().length"),0);
  console.log('CARRINHO UI PASS: dois produtos, remoção, quantidade editada, preço alterado exige revisão, venda ajustada R$8 e recarga sem duplicação; turno líquido R$3.');
  assert.equal(await js("window.StorageService.getVendas()[0].recebidoDinheiroCentavos"),1000);assert.equal(await js("window.StorageService.getVendas()[0].trocoCentavos"),700);
  assert.equal(await js("window.CaixaModule.calcularResumoFinanceiro(window.StorageService.getTurnoAtual()).totalDinheiro"),-2);
  assert.match(await read('local-cash-history'),/Recebido em dinheiro:.*10,00.*Troco:.*7,00/);
  assert.equal(await js("window.CaixaModule.calcularResumoFinanceiro(window.StorageService.getTurnoAtual()).totalPix"),2);
  assert.equal(await js("window.CaixaModule.calcularResumoFinanceiro(window.StorageService.getTurnoAtual()).totalDebito"),1);
  assert.equal(await js("window.CaixaModule.calcularResumoFinanceiro(window.StorageService.getTurnoAtual()).totalCredito"),2);
  assert.equal(await js("window.StorageService.getVendas()[0].ajuste.motivo"),'Acordo comercial');assert.equal(await js("window.StorageService.getVendas()[0].subtotal"),7);
  assert.equal(await js("Object.keys(localStorage).filter(k=>k.startsWith('flowpdv_rascunho_carrinho_v1:')).length"),0);console.log('RASCUNHO UI PASS: itens, ajustes e pagamentos recuperados; nova conferência obrigatória e rascunho removido após venda.');
  console.log('AJUSTE LOCAL UI PASS: subtotal 7, desconto 0.50, acréscimo 1.50, total 8; motivo e valores preservados.');
  console.log('DIVISAO LOCAL UI PASS: dinheiro 3, Pix 2, débito 1, crédito 2, recebido 10, troco 7; receita 8 e recarga sem duplicação.');

  await js("document.getElementById('checkout-close').click();document.getElementById('checkout-open').click();document.getElementById('recovery-current').click()");
  await wait("document.getElementById('checkout-dialog').dataset.busy === 'false' && document.getElementById('recovery-state').dataset.resultado === 'sem-divergencias'");
  assert.match(await read('recovery-state'), /Nenhum dado foi restaurado/);
  const recoveryOutput = path.resolve(__dirname, '../../output/etapa-8g'); fs.mkdirSync(recoveryOutput, { recursive: true });
  const recoverySize = win.getSize();
  for (const width of [1366, 1024]) {
    win.setSize(width, 768);
    await js("document.getElementById('recovery-title').scrollIntoView({block:'start'});new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))");
    fs.writeFileSync(path.join(recoveryOutput, 'conferencia-' + width + '.png'), (await win.webContents.capturePage(undefined, { stayHidden: true, stayAwake: true })).toPNG());
    assert.equal(await js("document.getElementById('checkout-dialog').scrollWidth <= document.getElementById('checkout-dialog').clientWidth + 1"), true);
    assert.equal(await js("document.getElementById('recovery-title').getBoundingClientRect().top >= document.querySelector('#checkout-dialog .checkout-header').getBoundingClientRect().bottom"), true);
  }
  win.setSize(...recoverySize);
  await js("document.getElementById('recovery-stock').click()");
  await wait("document.getElementById('checkout-dialog').dataset.busy === 'false' && document.getElementById('recovery-state').dataset.resultado === 'inventario-conferido'");
  assert.equal(await js("document.querySelectorAll('#recovery-inventory tbody tr').length"), 2);
  assert.match(await js("document.getElementById('recovery-inventory').textContent"), /2,25 kg/);
  assert.match(await js("document.getElementById('recovery-inventory').textContent"), /0,75 kg/);
  for (const width of [1366, 1024]) {
    win.setSize(width, 768);
    await js("document.getElementById('recovery-title').scrollIntoView({block:'start'});new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))");
    fs.writeFileSync(path.join(recoveryOutput, 'inventario-' + width + '.png'), (await win.webContents.capturePage(undefined, { stayHidden: true, stayAwake: true })).toPNG());
    assert.equal(await js("document.getElementById('checkout-dialog').scrollWidth <= document.getElementById('checkout-dialog').clientWidth + 1"), true);
  }
  win.setSize(...recoverySize);
  console.log('INVENTARIO CORTE UI PASS: dois vínculos, saldo atual após vendas e tabela sem sobrescrever estoque.');
  await js("document.getElementById('recovery-history').click()");
  await wait("document.getElementById('checkout-dialog').dataset.busy === 'false'");
  assert.equal(await js("document.getElementById('recovery-state').dataset.resultado"), 'conferencia-necessaria');
  assert.match(await read('recovery-state'), /3 turnos no arquivo e 3 no servidor/);
  assert.match(await read('recovery-state'), /Resumos do restaurante: 0 diferenças/);
  assert.match(await read('recovery-state'), /Aritmética da gaveta no arquivo:/);
  assert.match(await js("document.getElementById('checkout-dialog').textContent"), /Gaveta ainda aberta|Arquivo sem todos os campos/);
  // Diagnóstico de arquivo: remover um resumo não altera o histórico aberto do aplicativo.
  await js(`(() => {
    const dados = Object.fromEntries(['flowpdv_device_id','adega_vendas','adega_turno_atual','adega_turnos_historico'].map(k=>[k,localStorage.getItem(k)]));
    const historico = JSON.parse(dados.adega_turnos_historico); delete historico[0].restauranteV2; dados.adega_turnos_historico = JSON.stringify(historico);
    const pacote = {tipo:'flowpdv_homologacao_v2',versao:1,origem:{lojaId:'demo-loja-interface',terminalId:dados.flowpdv_device_id,terminalUid:${JSON.stringify(uid)}},dados};
    const dt = new DataTransfer(); dt.items.add(new File([JSON.stringify(pacote)],'backup-sem-resumo.json',{type:'application/json'}));
    const input = document.getElementById('recovery-file'); input.files = dt.files; input.dispatchEvent(new Event('change',{bubbles:true})); input.closest('details').open = true;
    document.getElementById('recovery-file-history').click();
  })()`);
  await wait("document.getElementById('checkout-dialog').dataset.busy === 'false'");
  assert.equal(await js("document.getElementById('recovery-state').dataset.resultado"), 'conferencia-necessaria');
  assert.match(await read('recovery-findings'), /Resumo encerrado do restaurante ausente/);
  assert.equal(await js("JSON.parse(localStorage.getItem('adega_turnos_historico')).every(t=>!!t.restauranteV2)"), true);
  const financialOutput = path.resolve(__dirname, '../../output/etapa-8s'); fs.mkdirSync(financialOutput, {recursive:true});
  for (const width of [1366,1024]) {
    win.setSize(width,768);
    await js("document.getElementById('recovery-state').scrollIntoView({block:'center'});new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))");
    fs.writeFileSync(path.join(financialOutput,'historico-'+width+'.png'), (await win.webContents.capturePage(undefined,{stayHidden:true,stayAwake:true})).toPNG());
    assert.equal(await js("document.getElementById('checkout-dialog').scrollWidth <= document.getElementById('checkout-dialog').clientWidth + 1"), true);
  }
  win.setSize(...recoverySize);
  console.log('FECHAMENTOS RECUPERACAO UI PASS: resumo ausente identificado no arquivo sem alterar o histórico local.');
  // Backup anterior à última venda: somente o arquivo fica sem esse registro.
  await js(`(() => {
    const chaves = ['flowpdv_device_id','adega_produtos','adega_produtos_backup_seguranca','adega_vendas','adega_turno_atual','adega_turnos_historico','adega_clientes','flowpdv_estoque_movimentos','flowpdv_ultimo_numero_venda','flowpdv_migracoes_estoque_teste'];
    const dados = Object.fromEntries(chaves.filter(k=>localStorage.getItem(k)!==null).map(k=>[k,localStorage.getItem(k)]));
    const turno = JSON.parse(dados.adega_turno_atual);
    dados.adega_vendas = JSON.stringify(JSON.parse(dados.adega_vendas).filter(v=>!(v.estoqueServidorV2 && v.turnoId===turno.id)));
    const pacote = {tipo:'flowpdv_homologacao_v2',versao:1,origem:{lojaId:'demo-loja-interface',terminalId:turno.terminalId,terminalUid:${JSON.stringify(uid)}},dados};
    const dt = new DataTransfer();dt.items.add(new File([JSON.stringify(pacote)],'backup-anterior.json',{type:'application/json'}));
    const input = document.getElementById('recovery-file');input.files=dt.files;input.dispatchEvent(new Event('change',{bubbles:true}));input.closest('details').open=true;
    document.getElementById('recovery-rebuild').click();
  })()`);
  await wait("document.getElementById('checkout-dialog').dataset.busy === 'false'");
  assert.equal(await js("document.getElementById('recovery-state').dataset.resultado"), 'copia-conferida');
  assert.match(await read('recovery-state'), /1 registro recuperado/);
  assert.equal(await js("window.StorageService.getVendas().length"), 3);
  // Troca de seleção após o início efetivo da consulta invalida a resposta tardia.
  await js("document.getElementById('recovery-rebuild').click()");
  await wait("document.getElementById('recovery-state').dataset.resultado === 'consultando'");
  await js("document.getElementById('recovery-file').dispatchEvent(new Event('change',{bubbles:true}))");
  await wait("document.getElementById('checkout-dialog').dataset.busy === 'false'");
  assert.equal(await js("document.getElementById('recovery-state').dataset.resultado"), 'erro');
  assert.equal(await js("document.getElementById('recovery-download').hidden"),true);
  await js("document.getElementById('recovery-rebuild').click()");
  await wait("document.getElementById('checkout-dialog').dataset.busy === 'false'");
  assert.equal(await js("document.getElementById('recovery-state').dataset.resultado"), 'copia-conferida');
  const rebuiltOutput = path.resolve(__dirname, '../../output/etapa-8n'); fs.mkdirSync(rebuiltOutput, {recursive:true});
  for (const width of [1366,1024]) {
    win.setSize(width,768);
    await js("document.getElementById('recovery-state').scrollIntoView({block:'center'});new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))");
    fs.writeFileSync(path.join(rebuiltOutput,'copia-'+width+'.png'),(await win.webContents.capturePage(undefined,{stayHidden:true,stayAwake:true})).toPNG());
    assert.equal(await js("document.getElementById('checkout-dialog').scrollWidth <= document.getElementById('checkout-dialog').clientWidth + 1"),true);
  }
  await js(`window.recoveryOldCreate = URL.createObjectURL; window.recoveryOldClick = HTMLAnchorElement.prototype.click;
    URL.createObjectURL = blob => { window.recoveryDownloaded = blob.text(); return 'blob:teste-recuperacao'; };
    HTMLAnchorElement.prototype.click = function() { if(this.download==='FlowPDV-backup-recuperado.json') window.recoveryDownloadSolicitado=true; else window.recoveryOldClick.call(this); };
    document.getElementById('recovery-download').click();`);
  await wait("document.getElementById('checkout-dialog').dataset.busy === 'false'");
  assert.equal(await js("window.recoveryDownloadSolicitado"), true);
  const downloaded = JSON.parse(await js("window.recoveryDownloaded"));
  assert.equal(JSON.parse(downloaded.dados.adega_vendas).length,3);
  assert.equal(JSON.parse(downloaded.dados.adega_vendas).filter(v=>v.recuperacaoV2).length,1);
  assert.equal(await js("window.StorageService.getVendas().length"),3);
  await js("URL.createObjectURL=window.recoveryOldCreate;HTMLAnchorElement.prototype.click=window.recoveryOldClick;void 0");
  assert.equal(await js("document.getElementById('recovery-download').hidden"),true);
  console.log('RECONSTRUCAO UI PASS: histórico de três turnos, cópia com venda posterior, download conferido sem alterar caixa.');
  await js("const dt=new DataTransfer();dt.items.add(new File(['{}'],'invalido.json',{type:'application/json'}));document.getElementById('recovery-file').files=dt.files;document.getElementById('recovery-check-file').click()");
  await wait("document.getElementById('checkout-dialog').dataset.busy === 'false' && document.getElementById('recovery-state').dataset.resultado === 'erro'");
  assert.match(await read('recovery-state'), /Backup incompatível/);
  assert.equal(await js("window.StorageService.getVendas().length"), 3);
  console.log('RECUPERACAO CONFERENCIA UI PASS: turno sem divergências, arquivo inválido recusado, dados preservados e duas resoluções.');

  await js("document.getElementById('checkout-close').click(); document.getElementById('pair-open').click()");
  await action("document.getElementById('pair-recover').click()");
  assert.match(await read('pair-terminal-state'), /Terminal ativo/);
  const output = path.resolve(__dirname, '../../output/parte-2-interface'); fs.mkdirSync(output, { recursive: true });
  fs.writeFileSync(path.join(output, 'pareamento-ativado.png'), (await win.webContents.capturePage()).toPNG());
  await fill({ 'pair-email': 'gerente-ui@example.test', 'pair-password': 'TesteLocal-123!' });
  await action("document.getElementById('pair-login-form').requestSubmit()");
  await fill({ 'pair-shop': 'demo-loja-interface', 'pair-target': uid });
  await js('window.confirm = () => true; void 0');
  await action("document.getElementById('pair-revoke').click()");
  assert.match(await read('pair-terminal-state'), /revogado/);
  await wait("document.getElementById('checkout-dialog').dataset.novasPermitidas === 'false'");
  assert.equal(await js("document.getElementById('classic-pdv-barcode-input').disabled"), true);
  assert.equal(await js("document.getElementById('op-add').disabled"), true);
  await action("document.getElementById('pair-recover').click()");
  assert.equal(await js("document.getElementById('pair-message').dataset.error"), 'true');
  assert.doesNotMatch(await read('pair-terminal-state'), /Terminal ativo/);
  await fill({ 'pair-transfer-source': uid, 'pair-transfer-target': 'caixa-recuperacao-ui', 'pair-transfer-reason': 'Computador anterior indisponível' });
  await action("document.getElementById('pair-transfer-apply').click()");
  assert.match(await read('pair-message'), /Confira a transferência novamente/);
  await action("document.getElementById('pair-transfer-plan').click()");
  assert.match(await read('pair-transfer-state'), /será revogado/);
  await js("document.getElementById('pair-transfer-target').dispatchEvent(new Event('input',{bubbles:true}))");
  await action("document.getElementById('pair-transfer-apply').click()");
  assert.match(await read('pair-message'), /Confira a transferência novamente/);
  await action("document.getElementById('pair-transfer-plan').click()");
  const transferOutput = path.resolve(__dirname, '../../output/etapa-8j'); fs.mkdirSync(transferOutput, { recursive: true });
  for (const width of [1366, 1024]) {
    win.setSize(width, 768);
    await js("document.getElementById('pair-transfer-section').scrollIntoView({block:'start'});new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))");
    fs.writeFileSync(path.join(transferOutput, 'transferencia-' + width + '.png'), (await win.webContents.capturePage(undefined, { stayHidden: true, stayAwake: true })).toPNG());
    assert.equal(await js("document.getElementById('pair-dialog').scrollWidth <= document.getElementById('pair-dialog').clientWidth + 1"), true);
  }
  await action("document.getElementById('pair-transfer-apply').click()");
  assert.match(await read('pair-transfer-state'), /Transferência concluída/);
  assert.equal(await js("Object.keys(localStorage).some(k=>k.startsWith('flowpdv_recuperacao_terminal_pendente:'))"), false);
  assert.equal(await js("window.StorageService.getVendas().length"), 3);
  await action("document.getElementById('pair-transfer-resume').click()");
  assert.match(await read('pair-message'), /Nenhuma recuperação pendente/);
  console.log('TRANSFERENCIA UI PASS: conferência obrigatória, edição invalida plano, transferência única, dados locais preservados.');
  console.log('UI PASS: login, isolamento entre lojas, autorização, ativação, logout separado, recuperação, recarga e revogação.');
};
