const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const ctx={};vm.createContext(ctx);vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../src/js/rascunho-carrinho-teste.js'),'utf8').replace('export function','function'),ctx);
const context={lojaId:'loja',terminalId:'terminal',turnoId:'T',dataAbertura:'2026-09-21T10:00:00Z'};
function fixture(){const map=new Map(),storage={getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)};return {map,storage,create:()=>ctx.criarRascunhoCarrinhoTeste({storage,ambienteTeste:true})};}
const draft=()=>({itens:[{id:'farinha',quantidade:'0,'}],campos:{'local-stock-cash':'10,','local-pay-pix':'2','local-discount':'0,50','local-surcharge':'1,50','local-adjust-reason':'Acordo comercial'}});
test('rascunho preserva texto incompleto e valores ao recriar o serviço',()=>{const f=fixture();f.create().salvar(context,draft());const d=f.create().carregar(context);assert.equal(d.itens[0].quantidade,'0,');assert.equal(d.campos['local-stock-cash'],'10,');assert.equal(d.campos['local-adjust-reason'],'Acordo comercial');});
test('loja, terminal, turno e data de abertura isolam rascunhos',()=>{const f=fixture();f.create().salvar(context,draft());for(const campo of Object.keys(context))assert.equal(f.create().carregar({...context,[campo]:'outro'}),null);f.create().remover({...context,lojaId:'outra'});assert.ok(f.create().carregar(context));});
test('rascunho descarta preços, identificadores de venda e confirmação',()=>{const f=fixture(),d=draft();d.itens[0].preco=1;d.vendaId='VL';d.confirmado=true;d.campos['local-stock-confirm']='true';f.create().salvar(context,d);const saved=f.create().carregar(context);assert.equal(saved.itens[0].preco,undefined);assert.equal(saved.vendaId,undefined);assert.equal(saved.confirmado,undefined);assert.equal(saved.campos['local-stock-confirm'],undefined);});
test('rascunho corrompido não é apagado silenciosamente',()=>{const f=fixture(),key=f.create().chave(context);for(const raw of ['{','null',JSON.stringify({versao:2,itens:[],campos:{}}),'x'.repeat(20001)]){f.map.set(key,raw);assert.throws(()=>f.create().carregar(context));assert.equal(f.map.get(key),raw);}f.create().remover(context);assert.equal(f.create().carregar(context),null);});
test('limites, duplicatas e contexto ausente recusam gravação',()=>{const f=fixture();for(const itens of [Array(31).fill({id:'x',quantidade:'1'}),[{id:'x',quantidade:'1'},{id:'x',quantidade:'2'}],[{id:'x',quantidade:1}]])assert.throws(()=>f.create().salvar(context,{itens,campos:{}}));assert.throws(()=>f.create().salvar(null,draft()));assert.equal(f.map.size,0);});
test('falha de gravação preserva versão anterior e falha de limpeza é propagada',()=>{const f=fixture();f.create().salvar(context,draft());const before=f.map.get(f.create().chave(context));f.storage.setItem=()=>{throw Error('Disco cheio');};assert.throws(()=>f.create().salvar(context,{itens:[],campos:{}}),/Disco/);assert.equal(f.map.get(f.create().chave(context)),before);f.storage.removeItem=()=>{throw Error('Falha ao remover');};assert.throws(()=>f.create().remover(context));});
test('perfil real não pode criar serviço de rascunho de teste',()=>{assert.throws(()=>ctx.criarRascunhoCarrinhoTeste({storage:{},ambienteTeste:false}));});
